echo "FT-Transformer (flatten)"
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fttransf_flatten --seed 1 --fieldtransf-nlayers 0 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/FTTransformer/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fttransf_flatten --seed 1 --fieldtransf-nlayers 0 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/FTTransformer/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fttransf_flatten --seed 1 --fieldtransf-nlayers 0 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/FTTransformer/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fttransf_flatten --seed 1 --fieldtransf-nlayers 0 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/FTTransformer/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fttransf_flatten --seed 2 --fieldtransf-nlayers 0 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/FTTransformer/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fttransf_flatten --seed 2 --fieldtransf-nlayers 0 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/FTTransformer/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fttransf_flatten --seed 2 --fieldtransf-nlayers 0 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/FTTransformer/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fttransf_flatten --seed 2 --fieldtransf-nlayers 0 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/FTTransformer/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fttransf_flatten --seed 3 --fieldtransf-nlayers 0 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/FTTransformer/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fttransf_flatten --seed 3 --fieldtransf-nlayers 0 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/FTTransformer/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fttransf_flatten --seed 3 --fieldtransf-nlayers 0 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/FTTransformer/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fttransf_flatten --seed 3 --fieldtransf-nlayers 0 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/FTTransformer/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fttransf_flatten --seed 4 --fieldtransf-nlayers 0 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/FTTransformer/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fttransf_flatten --seed 4 --fieldtransf-nlayers 0 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/FTTransformer/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fttransf_flatten --seed 4 --fieldtransf-nlayers 0 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/FTTransformer/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fttransf_flatten --seed 4 --fieldtransf-nlayers 0 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/FTTransformer/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fttransf_flatten --seed 5 --fieldtransf-nlayers 0 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/FTTransformer/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fttransf_flatten --seed 5 --fieldtransf-nlayers 0 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/FTTransformer/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fttransf_flatten --seed 5 --fieldtransf-nlayers 0 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/FTTransformer/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fttransf_flatten --seed 5 --fieldtransf-nlayers 0 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/FTTransformer/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb --col-emb

echo "Tabbie"
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family tabbie --seed 1 --fieldtransf-nlayers 4 --n-layers 0 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Tabbie/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family tabbie --seed 1 --fieldtransf-nlayers 4 --n-layers 0 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Tabbie/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family tabbie --seed 1 --fieldtransf-nlayers 4 --n-layers 0 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Tabbie/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family tabbie --seed 1 --fieldtransf-nlayers 4 --n-layers 0 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Tabbie/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family tabbie --seed 2 --fieldtransf-nlayers 4 --n-layers 0 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Tabbie/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family tabbie --seed 2 --fieldtransf-nlayers 4 --n-layers 0 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Tabbie/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family tabbie --seed 2 --fieldtransf-nlayers 4 --n-layers 0 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Tabbie/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family tabbie --seed 2 --fieldtransf-nlayers 4 --n-layers 0 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Tabbie/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family tabbie --seed 3 --fieldtransf-nlayers 4 --n-layers 0 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Tabbie/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family tabbie --seed 3 --fieldtransf-nlayers 4 --n-layers 0 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Tabbie/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family tabbie --seed 3 --fieldtransf-nlayers 4 --n-layers 0 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Tabbie/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family tabbie --seed 3 --fieldtransf-nlayers 4 --n-layers 0 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Tabbie/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family tabbie --seed 4 --fieldtransf-nlayers 4 --n-layers 0 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Tabbie/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family tabbie --seed 4 --fieldtransf-nlayers 4 --n-layers 0 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Tabbie/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family tabbie --seed 4 --fieldtransf-nlayers 4 --n-layers 0 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Tabbie/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family tabbie --seed 4 --fieldtransf-nlayers 4 --n-layers 0 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Tabbie/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family tabbie --seed 5 --fieldtransf-nlayers 4 --n-layers 0 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Tabbie/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family tabbie --seed 5 --fieldtransf-nlayers 4 --n-layers 0 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Tabbie/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family tabbie --seed 5 --fieldtransf-nlayers 4 --n-layers 0 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Tabbie/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family tabbie --seed 5 --fieldtransf-nlayers 4 --n-layers 0 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Tabbie/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb --col-emb

echo "More capacity in Final Transformer..."

echo "TabBERT (column-based)"
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family column_tabbert --seed 1 --fieldtransf-nlayers 1 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/ColumnTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family column_tabbert --seed 1 --fieldtransf-nlayers 1 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/ColumnTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family column_tabbert --seed 1 --fieldtransf-nlayers 1 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/ColumnTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family column_tabbert --seed 1 --fieldtransf-nlayers 1 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/ColumnTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family column_tabbert --seed 2 --fieldtransf-nlayers 1 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/ColumnTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family column_tabbert --seed 2 --fieldtransf-nlayers 1 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/ColumnTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family column_tabbert --seed 2 --fieldtransf-nlayers 1 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/ColumnTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family column_tabbert --seed 2 --fieldtransf-nlayers 1 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/ColumnTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family column_tabbert --seed 3 --fieldtransf-nlayers 1 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/ColumnTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family column_tabbert --seed 3 --fieldtransf-nlayers 1 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/ColumnTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family column_tabbert --seed 3 --fieldtransf-nlayers 1 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/ColumnTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family column_tabbert --seed 3 --fieldtransf-nlayers 1 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/ColumnTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family column_tabbert --seed 4 --fieldtransf-nlayers 1 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/ColumnTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family column_tabbert --seed 4 --fieldtransf-nlayers 1 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/ColumnTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family column_tabbert --seed 4 --fieldtransf-nlayers 1 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/ColumnTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family column_tabbert --seed 4 --fieldtransf-nlayers 1 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/ColumnTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family column_tabbert --seed 5 --fieldtransf-nlayers 1 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/ColumnTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family column_tabbert --seed 5 --fieldtransf-nlayers 1 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/ColumnTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family column_tabbert --seed 5 --fieldtransf-nlayers 1 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/ColumnTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family column_tabbert --seed 5 --fieldtransf-nlayers 1 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/ColumnTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb --col-emb

echo "TabBERT (row-based)"
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --dropout 0.3 --seed 1 --fieldtransf-nlayers 1 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/RowTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --dropout 0.3 --seed 1 --fieldtransf-nlayers 1 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/RowTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --dropout 0.3 --seed 1 --fieldtransf-nlayers 1 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/RowTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --dropout 0.3 --seed 1 --fieldtransf-nlayers 1 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/RowTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --dropout 0.3 --seed 2 --fieldtransf-nlayers 1 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/RowTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --dropout 0.3 --seed 2 --fieldtransf-nlayers 1 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/RowTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --dropout 0.3 --seed 2 --fieldtransf-nlayers 1 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/RowTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --dropout 0.3 --seed 2 --fieldtransf-nlayers 1 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/RowTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --dropout 0.3 --seed 3 --fieldtransf-nlayers 1 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/RowTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --dropout 0.3 --seed 3 --fieldtransf-nlayers 1 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/RowTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --dropout 0.3 --seed 3 --fieldtransf-nlayers 1 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/RowTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --dropout 0.3 --seed 3 --fieldtransf-nlayers 1 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/RowTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --dropout 0.3 --seed 4 --fieldtransf-nlayers 1 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/RowTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --dropout 0.3 --seed 4 --fieldtransf-nlayers 1 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/RowTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --dropout 0.3 --seed 4 --fieldtransf-nlayers 1 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/RowTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --dropout 0.3 --seed 4 --fieldtransf-nlayers 1 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/RowTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --dropout 0.3 --seed 5 --fieldtransf-nlayers 1 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/RowTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --dropout 0.3 --seed 5 --fieldtransf-nlayers 1 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/RowTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --dropout 0.3 --seed 5 --fieldtransf-nlayers 1 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/RowTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --dropout 0.3 --seed 5 --fieldtransf-nlayers 1 --n-layers 8 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/RowTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb --col-emb

echo "Fieldy (ours)"
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fieldy --seed 1 --fieldtransf-nlayers 2 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Fieldy/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fieldy --seed 1 --fieldtransf-nlayers 2 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Fieldy/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fieldy --seed 1 --fieldtransf-nlayers 2 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Fieldy/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fieldy --seed 1 --fieldtransf-nlayers 2 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Fieldy/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fieldy --seed 2 --fieldtransf-nlayers 2 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Fieldy/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fieldy --seed 2 --fieldtransf-nlayers 2 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Fieldy/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fieldy --seed 2 --fieldtransf-nlayers 2 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Fieldy/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fieldy --seed 2 --fieldtransf-nlayers 2 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Fieldy/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fieldy --seed 3 --fieldtransf-nlayers 2 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Fieldy/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fieldy --seed 3 --fieldtransf-nlayers 2 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Fieldy/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fieldy --seed 3 --fieldtransf-nlayers 2 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Fieldy/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fieldy --seed 3 --fieldtransf-nlayers 2 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Fieldy/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fieldy --seed 4 --fieldtransf-nlayers 2 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Fieldy/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fieldy --seed 4 --fieldtransf-nlayers 2 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Fieldy/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fieldy --seed 4 --fieldtransf-nlayers 2 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Fieldy/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fieldy --seed 4 --fieldtransf-nlayers 2 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Fieldy/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fieldy --seed 5 --fieldtransf-nlayers 2 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Fieldy/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fieldy --seed 5 --fieldtransf-nlayers 2 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Fieldy/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fieldy --seed 5 --fieldtransf-nlayers 2 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Fieldy/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fieldy --seed 5 --fieldtransf-nlayers 2 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Fieldy/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb --col-emb

echo "More capacity in Field Transformer..."

echo "TabBERT (column-based)"
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family column_tabbert --seed 1 --fieldtransf-nlayers 6 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/ColumnTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family column_tabbert --seed 1 --fieldtransf-nlayers 6 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/ColumnTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family column_tabbert --seed 1 --fieldtransf-nlayers 6 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/ColumnTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family column_tabbert --seed 1 --fieldtransf-nlayers 6 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/ColumnTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family column_tabbert --seed 2 --fieldtransf-nlayers 6 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/ColumnTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family column_tabbert --seed 2 --fieldtransf-nlayers 6 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/ColumnTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family column_tabbert --seed 2 --fieldtransf-nlayers 6 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/ColumnTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family column_tabbert --seed 2 --fieldtransf-nlayers 6 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/ColumnTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family column_tabbert --seed 3 --fieldtransf-nlayers 6 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/ColumnTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family column_tabbert --seed 3 --fieldtransf-nlayers 6 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/ColumnTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family column_tabbert --seed 3 --fieldtransf-nlayers 6 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/ColumnTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family column_tabbert --seed 3 --fieldtransf-nlayers 6 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/ColumnTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family column_tabbert --seed 4 --fieldtransf-nlayers 6 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/ColumnTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family column_tabbert --seed 4 --fieldtransf-nlayers 6 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/ColumnTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family column_tabbert --seed 4 --fieldtransf-nlayers 6 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/ColumnTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family column_tabbert --seed 4 --fieldtransf-nlayers 6 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/ColumnTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family column_tabbert --seed 5 --fieldtransf-nlayers 6 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/ColumnTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family column_tabbert --seed 5 --fieldtransf-nlayers 6 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/ColumnTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family column_tabbert --seed 5 --fieldtransf-nlayers 6 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/ColumnTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family column_tabbert --seed 5 --fieldtransf-nlayers 6 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/ColumnTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb --col-emb

echo "Fieldy (ours)"
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fieldy --seed 1 --fieldtransf-nlayers 5 --n-layers 4 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Fieldy/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fieldy --seed 1 --fieldtransf-nlayers 5 --n-layers 4 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Fieldy/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fieldy --seed 1 --fieldtransf-nlayers 5 --n-layers 4 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Fieldy/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fieldy --seed 1 --fieldtransf-nlayers 5 --n-layers 4 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Fieldy/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fieldy --seed 2 --fieldtransf-nlayers 5 --n-layers 4 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Fieldy/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fieldy --seed 2 --fieldtransf-nlayers 5 --n-layers 4 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Fieldy/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fieldy --seed 2 --fieldtransf-nlayers 5 --n-layers 4 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Fieldy/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fieldy --seed 2 --fieldtransf-nlayers 5 --n-layers 4 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Fieldy/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fieldy --seed 3 --fieldtransf-nlayers 5 --n-layers 4 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Fieldy/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fieldy --seed 3 --fieldtransf-nlayers 5 --n-layers 4 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Fieldy/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fieldy --seed 3 --fieldtransf-nlayers 5 --n-layers 4 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Fieldy/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fieldy --seed 3 --fieldtransf-nlayers 5 --n-layers 4 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Fieldy/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fieldy --seed 4 --fieldtransf-nlayers 5 --n-layers 4 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Fieldy/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fieldy --seed 4 --fieldtransf-nlayers 5 --n-layers 4 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Fieldy/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fieldy --seed 4 --fieldtransf-nlayers 5 --n-layers 4 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Fieldy/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fieldy --seed 4 --fieldtransf-nlayers 5 --n-layers 4 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Fieldy/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fieldy --seed 5 --fieldtransf-nlayers 5 --n-layers 4 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Fieldy/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fieldy --seed 5 --fieldtransf-nlayers 5 --n-layers 4 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Fieldy/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fieldy --seed 5 --fieldtransf-nlayers 5 --n-layers 4 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Fieldy/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --dropout 0.3 --family fieldy --seed 5 --fieldtransf-nlayers 5 --n-layers 4 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/Fieldy/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb --col-emb

echo "TabBERT (row-based)"
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --dropout 0.3 --seed 1 --fieldtransf-nlayers 6 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/RowTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --dropout 0.3 --seed 1 --fieldtransf-nlayers 6 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/RowTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --dropout 0.3 --seed 1 --fieldtransf-nlayers 6 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/RowTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --dropout 0.3 --seed 1 --fieldtransf-nlayers 6 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/RowTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --dropout 0.3 --seed 2 --fieldtransf-nlayers 6 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/RowTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --dropout 0.3 --seed 2 --fieldtransf-nlayers 6 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/RowTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --dropout 0.3 --seed 2 --fieldtransf-nlayers 6 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/RowTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --dropout 0.3 --seed 2 --fieldtransf-nlayers 6 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/RowTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --dropout 0.3 --seed 3 --fieldtransf-nlayers 6 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/RowTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --dropout 0.3 --seed 3 --fieldtransf-nlayers 6 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/RowTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --dropout 0.3 --seed 3 --fieldtransf-nlayers 6 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/RowTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --dropout 0.3 --seed 3 --fieldtransf-nlayers 6 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/RowTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --dropout 0.3 --seed 4 --fieldtransf-nlayers 6 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/RowTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --dropout 0.3 --seed 4 --fieldtransf-nlayers 6 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/RowTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --dropout 0.3 --seed 4 --fieldtransf-nlayers 6 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/RowTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --dropout 0.3 --seed 4 --fieldtransf-nlayers 6 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/RowTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --dropout 0.3 --seed 5 --fieldtransf-nlayers 6 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/RowTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --dropout 0.3 --seed 5 --fieldtransf-nlayers 6 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/RowTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --dropout 0.3 --seed 5 --fieldtransf-nlayers 6 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/RowTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --dropout 0.3 --seed 5 --fieldtransf-nlayers 6 --n-layers 6 --n-heads 10 --runs 1 --bs 100 --hidden-size 500 --data-type kdd --mlm --mlm-loss all --output-dir ./results/kdd/60pt_20ft/RowTabBERT/ --pre-train --pt-epochs 60 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --pos-emb --col-emb

