echo "FT-Transformer (flatten)"
CUDA_VISIBLE_DEVICES=0 python main.py --family fttransf_flatten --seed 1 --fieldtransf-nlayers 0 --n-layers 14 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/FTTransformer/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std
CUDA_VISIBLE_DEVICES=0 python main.py --family fttransf_flatten --seed 1 --fieldtransf-nlayers 0 --n-layers 14 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/FTTransformer/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family fttransf_flatten --seed 1 --fieldtransf-nlayers 0 --n-layers 14 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/FTTransformer/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family fttransf_flatten --seed 1 --fieldtransf-nlayers 0 --n-layers 14 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/FTTransformer/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --family fttransf_flatten --seed 2 --fieldtransf-nlayers 0 --n-layers 14 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/FTTransformer/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std
CUDA_VISIBLE_DEVICES=0 python main.py --family fttransf_flatten --seed 2 --fieldtransf-nlayers 0 --n-layers 14 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/FTTransformer/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family fttransf_flatten --seed 2 --fieldtransf-nlayers 0 --n-layers 14 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/FTTransformer/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family fttransf_flatten --seed 2 --fieldtransf-nlayers 0 --n-layers 14 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/FTTransformer/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --family fttransf_flatten --seed 3 --fieldtransf-nlayers 0 --n-layers 14 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/FTTransformer/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std
CUDA_VISIBLE_DEVICES=0 python main.py --family fttransf_flatten --seed 3 --fieldtransf-nlayers 0 --n-layers 14 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/FTTransformer/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family fttransf_flatten --seed 3 --fieldtransf-nlayers 0 --n-layers 14 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/FTTransformer/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family fttransf_flatten --seed 3 --fieldtransf-nlayers 0 --n-layers 14 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/FTTransformer/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --family fttransf_flatten --seed 4 --fieldtransf-nlayers 0 --n-layers 14 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/FTTransformer/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std
CUDA_VISIBLE_DEVICES=0 python main.py --family fttransf_flatten --seed 4 --fieldtransf-nlayers 0 --n-layers 14 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/FTTransformer/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family fttransf_flatten --seed 4 --fieldtransf-nlayers 0 --n-layers 14 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/FTTransformer/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family fttransf_flatten --seed 4 --fieldtransf-nlayers 0 --n-layers 14 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/FTTransformer/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --family fttransf_flatten --seed 5 --fieldtransf-nlayers 0 --n-layers 14 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/FTTransformer/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std
CUDA_VISIBLE_DEVICES=0 python main.py --family fttransf_flatten --seed 5 --fieldtransf-nlayers 0 --n-layers 14 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/FTTransformer/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family fttransf_flatten --seed 5 --fieldtransf-nlayers 0 --n-layers 14 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/FTTransformer/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family fttransf_flatten --seed 5 --fieldtransf-nlayers 0 --n-layers 14 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/FTTransformer/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb --col-emb

echo "Tabbie"
CUDA_VISIBLE_DEVICES=0 python main.py --family tabbie --seed 1 --fieldtransf-nlayers 4 --n-layers 0 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Tabbie/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std
CUDA_VISIBLE_DEVICES=0 python main.py --family tabbie --seed 1 --fieldtransf-nlayers 4 --n-layers 0 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Tabbie/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family tabbie --seed 1 --fieldtransf-nlayers 4 --n-layers 0 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Tabbie/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family tabbie --seed 1 --fieldtransf-nlayers 4 --n-layers 0 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Tabbie/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --family tabbie --seed 2 --fieldtransf-nlayers 4 --n-layers 0 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Tabbie/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std
CUDA_VISIBLE_DEVICES=0 python main.py --family tabbie --seed 2 --fieldtransf-nlayers 4 --n-layers 0 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Tabbie/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family tabbie --seed 2 --fieldtransf-nlayers 4 --n-layers 0 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Tabbie/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family tabbie --seed 2 --fieldtransf-nlayers 4 --n-layers 0 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Tabbie/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --family tabbie --seed 3 --fieldtransf-nlayers 4 --n-layers 0 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Tabbie/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std
CUDA_VISIBLE_DEVICES=0 python main.py --family tabbie --seed 3 --fieldtransf-nlayers 4 --n-layers 0 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Tabbie/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family tabbie --seed 3 --fieldtransf-nlayers 4 --n-layers 0 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Tabbie/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family tabbie --seed 3 --fieldtransf-nlayers 4 --n-layers 0 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Tabbie/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --family tabbie --seed 4 --fieldtransf-nlayers 4 --n-layers 0 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Tabbie/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std
CUDA_VISIBLE_DEVICES=0 python main.py --family tabbie --seed 4 --fieldtransf-nlayers 4 --n-layers 0 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Tabbie/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family tabbie --seed 4 --fieldtransf-nlayers 4 --n-layers 0 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Tabbie/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family tabbie --seed 4 --fieldtransf-nlayers 4 --n-layers 0 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Tabbie/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --family tabbie --seed 5 --fieldtransf-nlayers 4 --n-layers 0 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Tabbie/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std
CUDA_VISIBLE_DEVICES=0 python main.py --family tabbie --seed 5 --fieldtransf-nlayers 4 --n-layers 0 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Tabbie/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family tabbie --seed 5 --fieldtransf-nlayers 4 --n-layers 0 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Tabbie/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family tabbie --seed 5 --fieldtransf-nlayers 4 --n-layers 0 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Tabbie/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb --col-emb

echo "More capacity in Final Transformer..."

echo "TabBERT (column-based)"
CUDA_VISIBLE_DEVICES=0 python main.py --family column_tabbert --seed 1 --fieldtransf-nlayers 1 --n-layers 12 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/ColumnTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std
CUDA_VISIBLE_DEVICES=0 python main.py --family column_tabbert --seed 1 --fieldtransf-nlayers 1 --n-layers 12 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/ColumnTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family column_tabbert --seed 1 --fieldtransf-nlayers 1 --n-layers 12 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/ColumnTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family column_tabbert --seed 1 --fieldtransf-nlayers 1 --n-layers 12 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/ColumnTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --family column_tabbert --seed 2 --fieldtransf-nlayers 1 --n-layers 12 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/ColumnTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std
CUDA_VISIBLE_DEVICES=0 python main.py --family column_tabbert --seed 2 --fieldtransf-nlayers 1 --n-layers 12 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/ColumnTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family column_tabbert --seed 2 --fieldtransf-nlayers 1 --n-layers 12 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/ColumnTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family column_tabbert --seed 2 --fieldtransf-nlayers 1 --n-layers 12 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/ColumnTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --family column_tabbert --seed 3 --fieldtransf-nlayers 1 --n-layers 12 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/ColumnTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std
CUDA_VISIBLE_DEVICES=0 python main.py --family column_tabbert --seed 3 --fieldtransf-nlayers 1 --n-layers 12 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/ColumnTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family column_tabbert --seed 3 --fieldtransf-nlayers 1 --n-layers 12 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/ColumnTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family column_tabbert --seed 3 --fieldtransf-nlayers 1 --n-layers 12 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/ColumnTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --family column_tabbert --seed 4 --fieldtransf-nlayers 1 --n-layers 12 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/ColumnTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std
CUDA_VISIBLE_DEVICES=0 python main.py --family column_tabbert --seed 4 --fieldtransf-nlayers 1 --n-layers 12 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/ColumnTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family column_tabbert --seed 4 --fieldtransf-nlayers 1 --n-layers 12 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/ColumnTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family column_tabbert --seed 4 --fieldtransf-nlayers 1 --n-layers 12 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/ColumnTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --family column_tabbert --seed 5 --fieldtransf-nlayers 1 --n-layers 12 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/ColumnTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std
CUDA_VISIBLE_DEVICES=0 python main.py --family column_tabbert --seed 5 --fieldtransf-nlayers 1 --n-layers 12 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/ColumnTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family column_tabbert --seed 5 --fieldtransf-nlayers 1 --n-layers 12 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/ColumnTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family column_tabbert --seed 5 --fieldtransf-nlayers 1 --n-layers 12 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/ColumnTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb --col-emb

echo "TabBERT (row-based)"
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --seed 1 --fieldtransf-nlayers 1 --n-layers 12 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/RowTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --seed 1 --fieldtransf-nlayers 1 --n-layers 12 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/RowTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --seed 1 --fieldtransf-nlayers 1 --n-layers 12 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/RowTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --seed 1 --fieldtransf-nlayers 1 --n-layers 12 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/RowTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --seed 2 --fieldtransf-nlayers 1 --n-layers 12 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/RowTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --seed 2 --fieldtransf-nlayers 1 --n-layers 12 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/RowTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --seed 2 --fieldtransf-nlayers 1 --n-layers 12 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/RowTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --seed 2 --fieldtransf-nlayers 1 --n-layers 12 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/RowTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --seed 3 --fieldtransf-nlayers 1 --n-layers 12 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/RowTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --seed 3 --fieldtransf-nlayers 1 --n-layers 12 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/RowTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --seed 3 --fieldtransf-nlayers 1 --n-layers 12 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/RowTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --seed 3 --fieldtransf-nlayers 1 --n-layers 12 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/RowTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --seed 4 --fieldtransf-nlayers 1 --n-layers 12 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/RowTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --seed 4 --fieldtransf-nlayers 1 --n-layers 12 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/RowTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --seed 4 --fieldtransf-nlayers 1 --n-layers 12 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/RowTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --seed 4 --fieldtransf-nlayers 1 --n-layers 12 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/RowTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --seed 5 --fieldtransf-nlayers 1 --n-layers 12 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/RowTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --seed 5 --fieldtransf-nlayers 1 --n-layers 12 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/RowTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --seed 5 --fieldtransf-nlayers 1 --n-layers 12 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/RowTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --seed 5 --fieldtransf-nlayers 1 --n-layers 12 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/RowTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb --col-emb

echo "Fieldy"
CUDA_VISIBLE_DEVICES=0 python main.py --family fieldy --seed 1 --fieldtransf-nlayers 2 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Fieldy/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std
CUDA_VISIBLE_DEVICES=0 python main.py --family fieldy --seed 1 --fieldtransf-nlayers 2 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Fieldy/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family fieldy --seed 1 --fieldtransf-nlayers 2 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Fieldy/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family fieldy --seed 1 --fieldtransf-nlayers 2 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Fieldy/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --family fieldy --seed 2 --fieldtransf-nlayers 2 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Fieldy/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std
CUDA_VISIBLE_DEVICES=0 python main.py --family fieldy --seed 2 --fieldtransf-nlayers 2 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Fieldy/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family fieldy --seed 2 --fieldtransf-nlayers 2 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Fieldy/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family fieldy --seed 2 --fieldtransf-nlayers 2 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Fieldy/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --family fieldy --seed 3 --fieldtransf-nlayers 2 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Fieldy/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std
CUDA_VISIBLE_DEVICES=0 python main.py --family fieldy --seed 3 --fieldtransf-nlayers 2 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Fieldy/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family fieldy --seed 3 --fieldtransf-nlayers 2 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Fieldy/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family fieldy --seed 3 --fieldtransf-nlayers 2 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Fieldy/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --family fieldy --seed 4 --fieldtransf-nlayers 2 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Fieldy/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std
CUDA_VISIBLE_DEVICES=0 python main.py --family fieldy --seed 4 --fieldtransf-nlayers 2 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Fieldy/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family fieldy --seed 4 --fieldtransf-nlayers 2 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Fieldy/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family fieldy --seed 4 --fieldtransf-nlayers 2 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Fieldy/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --family fieldy --seed 5 --fieldtransf-nlayers 2 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Fieldy/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std
CUDA_VISIBLE_DEVICES=0 python main.py --family fieldy --seed 5 --fieldtransf-nlayers 2 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Fieldy/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family fieldy --seed 5 --fieldtransf-nlayers 2 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Fieldy/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family fieldy --seed 5 --fieldtransf-nlayers 2 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Fieldy/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb --col-emb

echo "More capacity in Field Transformer..."

echo "TabBERT (column-based)"
CUDA_VISIBLE_DEVICES=0 python main.py --family column_tabbert --seed 1 --fieldtransf-nlayers 6 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/ColumnTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std
CUDA_VISIBLE_DEVICES=0 python main.py --family column_tabbert --seed 1 --fieldtransf-nlayers 6 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/ColumnTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family column_tabbert --seed 1 --fieldtransf-nlayers 6 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/ColumnTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family column_tabbert --seed 1 --fieldtransf-nlayers 6 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/ColumnTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --family column_tabbert --seed 2 --fieldtransf-nlayers 6 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/ColumnTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std
CUDA_VISIBLE_DEVICES=0 python main.py --family column_tabbert --seed 2 --fieldtransf-nlayers 6 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/ColumnTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family column_tabbert --seed 2 --fieldtransf-nlayers 6 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/ColumnTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family column_tabbert --seed 2 --fieldtransf-nlayers 6 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/ColumnTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --family column_tabbert --seed 3 --fieldtransf-nlayers 6 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/ColumnTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std
CUDA_VISIBLE_DEVICES=0 python main.py --family column_tabbert --seed 3 --fieldtransf-nlayers 6 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/ColumnTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family column_tabbert --seed 3 --fieldtransf-nlayers 6 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/ColumnTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family column_tabbert --seed 3 --fieldtransf-nlayers 6 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/ColumnTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --family column_tabbert --seed 4 --fieldtransf-nlayers 6 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/ColumnTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std
CUDA_VISIBLE_DEVICES=0 python main.py --family column_tabbert --seed 4 --fieldtransf-nlayers 6 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/ColumnTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family column_tabbert --seed 4 --fieldtransf-nlayers 6 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/ColumnTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family column_tabbert --seed 4 --fieldtransf-nlayers 6 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/ColumnTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --family column_tabbert --seed 5 --fieldtransf-nlayers 6 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/ColumnTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std
CUDA_VISIBLE_DEVICES=0 python main.py --family column_tabbert --seed 5 --fieldtransf-nlayers 6 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/ColumnTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family column_tabbert --seed 5 --fieldtransf-nlayers 6 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/ColumnTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family column_tabbert --seed 5 --fieldtransf-nlayers 6 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/ColumnTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb --col-emb

echo "TabBERT (row-based)"
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --seed 1 --fieldtransf-nlayers 6 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/RowTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --seed 1 --fieldtransf-nlayers 6 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/RowTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --seed 1 --fieldtransf-nlayers 6 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/RowTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --seed 1 --fieldtransf-nlayers 6 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/RowTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --seed 2 --fieldtransf-nlayers 6 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/RowTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --seed 2 --fieldtransf-nlayers 6 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/RowTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --seed 2 --fieldtransf-nlayers 6 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/RowTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --seed 2 --fieldtransf-nlayers 6 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/RowTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --seed 3 --fieldtransf-nlayers 6 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/RowTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --seed 3 --fieldtransf-nlayers 6 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/RowTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --seed 3 --fieldtransf-nlayers 6 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/RowTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --seed 3 --fieldtransf-nlayers 6 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/RowTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --seed 4 --fieldtransf-nlayers 6 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/RowTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --seed 4 --fieldtransf-nlayers 6 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/RowTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --seed 4 --fieldtransf-nlayers 6 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/RowTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --seed 4 --fieldtransf-nlayers 6 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/RowTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --seed 5 --fieldtransf-nlayers 6 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/RowTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --seed 5 --fieldtransf-nlayers 6 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/RowTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --seed 5 --fieldtransf-nlayers 6 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/RowTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family row_tabbert --seed 5 --fieldtransf-nlayers 6 --n-layers 10 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/RowTabBERT/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb --col-emb

echo "Fieldy"
CUDA_VISIBLE_DEVICES=0 python main.py --family fieldy --seed 1 --fieldtransf-nlayers 8 --n-layers 4 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Fieldy/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std
CUDA_VISIBLE_DEVICES=0 python main.py --family fieldy --seed 1 --fieldtransf-nlayers 8 --n-layers 4 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Fieldy/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family fieldy --seed 1 --fieldtransf-nlayers 8 --n-layers 4 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Fieldy/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family fieldy --seed 1 --fieldtransf-nlayers 8 --n-layers 4 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Fieldy/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --family fieldy --seed 2 --fieldtransf-nlayers 8 --n-layers 4 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Fieldy/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std
CUDA_VISIBLE_DEVICES=0 python main.py --family fieldy --seed 2 --fieldtransf-nlayers 8 --n-layers 4 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Fieldy/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family fieldy --seed 2 --fieldtransf-nlayers 8 --n-layers 4 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Fieldy/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family fieldy --seed 2 --fieldtransf-nlayers 8 --n-layers 4 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Fieldy/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --family fieldy --seed 3 --fieldtransf-nlayers 8 --n-layers 4 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Fieldy/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std
CUDA_VISIBLE_DEVICES=0 python main.py --family fieldy --seed 3 --fieldtransf-nlayers 8 --n-layers 4 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Fieldy/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family fieldy --seed 3 --fieldtransf-nlayers 8 --n-layers 4 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Fieldy/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family fieldy --seed 3 --fieldtransf-nlayers 8 --n-layers 4 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Fieldy/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --family fieldy --seed 4 --fieldtransf-nlayers 8 --n-layers 4 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Fieldy/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std
CUDA_VISIBLE_DEVICES=0 python main.py --family fieldy --seed 4 --fieldtransf-nlayers 8 --n-layers 4 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Fieldy/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family fieldy --seed 4 --fieldtransf-nlayers 8 --n-layers 4 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Fieldy/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family fieldy --seed 4 --fieldtransf-nlayers 8 --n-layers 4 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Fieldy/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb --col-emb

CUDA_VISIBLE_DEVICES=0 python main.py --family fieldy --seed 5 --fieldtransf-nlayers 8 --n-layers 4 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Fieldy/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std
CUDA_VISIBLE_DEVICES=0 python main.py --family fieldy --seed 5 --fieldtransf-nlayers 8 --n-layers 4 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Fieldy/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family fieldy --seed 5 --fieldtransf-nlayers 8 --n-layers 4 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Fieldy/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --col-emb
CUDA_VISIBLE_DEVICES=0 python main.py --family fieldy --seed 5 --fieldtransf-nlayers 8 --n-layers 4 --n-heads 10 --runs 1 --bs 64 --hidden-size 800 --data-type prsa --mlm --mlm-loss all --output-dir ./results/prsa/Fieldy/ --pre-train --pt-epochs 24 --fine-tune --ft-epochs 20 --fieldtransf-nheads 10 --mse --scale-targets --scaling std --pos-emb --col-emb
